version: '3.7'
services:
    server:
        build:
            context: .
        ports:
            - 80:80
        environment:
            PORT: 80
        container_name: personal-website-server
networks:
    default:
        external:
            name: teaclub
