version: '3.7'
services:
    server:
        build:
            context: .
        ports:
            - 5000:5000
        container_name: server
networks:
    default:
        external:
            name: teaclub
