version: '3.7'
services:
    server:
        build:
            context: .
            target: development
        ports:
            - 5000:5000
        volumes:
            - "./:/go/src/personal-website-server/"
        container_name: server
networks:
  default:
    external:
        name: teaclub
